from typing import Optional

class Network:
    Main: Network
    Test: Network

class ZcashAddress:
    @staticmethod
    def parse(s: str) -> ZcashAddress: ...
    def encode(self) -> str: ...
    def network(self) -> Network: ...
    def address_type(self) -> str: ...
    def is_shielded(self) -> bool: ...
    def can_receive_memo(self) -> bool: ...

class Payment:
    def __init__(
        self,
        address: ZcashAddress,
        amount: int,
        memo: Optional[bytes] = None,
        label: Optional[str] = None,
        message: Optional[str] = None,
    ) -> None: ...
    @property
    def address(self) -> ZcashAddress: ...
    @property
    def amount(self) -> int: ...
    @property
    def amount_zec(self) -> float: ...
    @property
    def memo(self) -> Optional[bytes]: ...
    @property
    def memo_text(self) -> Optional[str]: ...
    @property
    def label(self) -> Optional[str]: ...
    @property
    def message(self) -> Optional[str]: ...

class TransactionRequest:
    @staticmethod
    def from_uri(uri: str) -> TransactionRequest: ...
    @staticmethod
    def new(payments: list[Payment]) -> TransactionRequest: ...
    def to_uri(self) -> str: ...
    @property
    def payments(self) -> list[Payment]: ...
    def total(self) -> int: ...
    def total_zec(self) -> float: ...
    def __len__(self) -> int: ...

class UnifiedSpendingKey:
    @staticmethod
    def from_seed(
        seed: bytes, network: Network, account: int = 0
    ) -> UnifiedSpendingKey: ...
    def to_unified_full_viewing_key(self) -> UnifiedFullViewingKey: ...
    def default_address(self) -> UnifiedAddress: ...

class UnifiedFullViewingKey:
    def encode(self) -> str: ...
    @staticmethod
    def decode(encoded: str, network: Network) -> UnifiedFullViewingKey: ...
    def default_address(self) -> UnifiedAddress: ...
    def network(self) -> Network: ...

class UnifiedAddress:
    def encode(self) -> str: ...
    def to_zcash_address(self) -> ZcashAddress: ...
    def has_orchard(self) -> bool: ...
    def has_sapling(self) -> bool: ...
    def has_transparent(self) -> bool: ...
    def network(self) -> Network: ...

class PyZcashError(Exception): ...
class AddressParseError(PyZcashError): ...
class Zip321Error(PyZcashError): ...
class KeyDerivationError(PyZcashError): ...
